/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;
import Model.Produk;
import Model.Pelanggan;
import Model.TPenjualan;
import Controller.PelangganController;
import Controller.TPenjualanController;
import Controller.ProdukController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import Exception.InputKosongException;
import Model.BJual;
import Controller.BJualController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import table.detailJualTable;
/**
 *
 * @author LENOVO
 */
public class KasirPanel extends javax.swing.JPanel {
    private TPenjualanController dataControl = new TPenjualanController();
    private ProdukController PrC = new ProdukController();
    private BJualController BLC = new BJualController();
    private PelangganController PlC = new PelangganController();
    private Produk P = null;
    private Pelanggan PL = null;
    private TPenjualan dataModel = null;
    String actionProduk = null;
    String actionPelanggan = null;
    String actionTransaksi = null;
    String idProduk = "";
    String idTransaksi = "";
    String idPelanggan = "";
    
    private Component rootPane;
    List<Pelanggan> singleList;
    List<Produk> pr = new ArrayList<>();
    List<Integer> Jumlah = new ArrayList<>();
    double totalHarga = 0;
    int counter = 0;
    /**
     * Creates new form
     */
    public KasirPanel() {
        initComponents();
//        setOpaque(false);
        totalHargaTextArea.setEnabled(false);
        setPelangganToDropdown();
        clearText();
        totalHargaTextArea.setEnabled(false);
        supplierDropdown.setSelectedIndex(-1);
        totalHargaTextArea.setText("");

    }
    
    public void setPelangganToDropdown(){
        singleList = PlC.showListPelanggan();
        System.out.println(singleList.size());
        for(int i = 0; i < singleList.size(); i++){
            supplierDropdown.addItem(singleList.get(i));
            System.out.println(singleList.get(i).getNama());
        }
       
    }
    
    // RESET METHOD TO DEFAULT
    public void clearText(){
        searchKodeProdukInput.setText("");
        jumlahProdukInput.setText("");
        
        
    }
    
    // SET METHOD BUTTON EDIT & DELETE
    public void setEditDeleteBtn(boolean value){
    }
    
    public void InputKeTableTemp(){
        DefaultTableModel tblModel = (DefaultTableModel)kasirTable.getModel();
        Object rowData[] = new Object[5];
        for (int i = counter; i < Jumlah.size(); i++) {
            rowData[0] = counter + 1;
            rowData[1] = pr.get(i).getNama();
            rowData[2] = pr.get(i).getHarga_satuan();
            rowData[3] = Jumlah.get(i);
            rowData[4] = pr.get(i).getHarga_satuan() * Jumlah.get(i);
            tblModel.addRow(rowData);
            totalHarga += pr.get(i).getHarga_satuan() * Jumlah.get(i);
        }
        
    }
    public void SearchProdukNyaNgab(String kode,int Jumlah){
        P=PrC.searchProduk(kode);
        if((P.getJumlah()-Jumlah)<0){
            JOptionPane.showMessageDialog(rootPane, "Habis Stok Ngab");
            return;
        }
        InputKeArrayList(Jumlah, P);
    }
    public void InputKeArrayList(int jumlah, Produk E){
        Jumlah.add(jumlah);
        pr.add(E);
        InputKeTableTemp();
        totalHargaTextArea.setText(""+totalHarga);
        counter+=1;
    }
    
    public void inputKosongPembelianException() throws InputKosongException{
        if(pr.isEmpty() || supplierDropdown.getSelectedIndex() == -1){
            throw new InputKosongException();
        }        
    }
    
    public void jumlahKosongPembelianException() throws InputKosongException{
        if(jumlahProdukInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInputLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        kodeProdukPanel = new javax.swing.JPanel();
        KodeProdukPanel = new javax.swing.JLabel();
        kodeProdukInput = new javax.swing.JTextField();
        namaProdukPanel = new javax.swing.JPanel();
        namaData2Panel = new javax.swing.JLabel();
        namaProdukInput = new javax.swing.JTextField();
        jenisProdukRadioPanel = new javax.swing.JPanel();
        radioLabel = new javax.swing.JLabel();
        radioData1 = new javax.swing.JRadioButton();
        radioData2 = new javax.swing.JRadioButton();
        radioData3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        hargaSatuanLabel = new javax.swing.JLabel();
        hargaSatuanInput = new javax.swing.JTextField();
        jumlahInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTable = new javax.swing.JTable();
        mainPanel1 = new javax.swing.JPanel();
        searchInputPanel1 = new javax.swing.JPanel();
        searchInputLabel1 = new javax.swing.JLabel();
        searchKodeProdukInput = new javax.swing.JTextField();
        searchkodeProdukButton = new javax.swing.JButton();
        dataFormPanel1 = new javax.swing.JPanel();
        kodeProdukPanel1 = new javax.swing.JPanel();
        totalHargaTextArea = new javax.swing.JTextField();
        cancelButton1 = new javax.swing.JButton();
        totalHargapanel = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        jumlahProdukInput = new javax.swing.JTextField();
        JumlahPanel = new javax.swing.JLabel();
        idPelangganPanel = new javax.swing.JLabel();
        supplierDropdown = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        kasirTable = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInputLabel.setText("Pencarian Produk");

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        dataFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kodeProdukPanel.setBackground(new java.awt.Color(255, 255, 255));

        KodeProdukPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        KodeProdukPanel.setText("Kode Produk");

        kodeProdukInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        kodeProdukInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeProdukInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kodeProdukPanelLayout = new javax.swing.GroupLayout(kodeProdukPanel);
        kodeProdukPanel.setLayout(kodeProdukPanelLayout);
        kodeProdukPanelLayout.setHorizontalGroup(
            kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KodeProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                        .addComponent(kodeProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodeProdukPanelLayout.setVerticalGroup(
            kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(KodeProdukPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        namaProdukPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaData2Panel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaData2Panel.setText("Nama Produk");

        namaProdukInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namaProdukInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaProdukInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaProdukPanelLayout = new javax.swing.GroupLayout(namaProdukPanel);
        namaProdukPanel.setLayout(namaProdukPanelLayout);
        namaProdukPanelLayout.setHorizontalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaData2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(namaProdukPanelLayout.createSequentialGroup()
                        .addComponent(namaProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        namaProdukPanelLayout.setVerticalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaData2Panel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jenisProdukRadioPanel.setBackground(new java.awt.Color(255, 255, 255));

        radioLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioLabel.setText("Jenis Produk");

        radioData1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData1.setText("Alat Rumah Tangga");
        radioData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData1ActionPerformed(evt);
            }
        });

        radioData2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData2.setText("Makanan dan Minuman");
        radioData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData2ActionPerformed(evt);
            }
        });

        radioData3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData3.setText("Kecantikan");

        javax.swing.GroupLayout jenisProdukRadioPanelLayout = new javax.swing.GroupLayout(jenisProdukRadioPanel);
        jenisProdukRadioPanel.setLayout(jenisProdukRadioPanelLayout);
        jenisProdukRadioPanelLayout.setHorizontalGroup(
            jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisProdukRadioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLabel)
                    .addComponent(radioData1)
                    .addComponent(radioData2)
                    .addComponent(radioData3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jenisProdukRadioPanelLayout.setVerticalGroup(
            jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisProdukRadioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        hargaSatuanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaSatuanLabel.setText("Harga Satuan");

        hargaSatuanInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        hargaSatuanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSatuanInputActionPerformed(evt);
            }
        });

        jumlahInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jumlahInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaSatuanLabel)
                    .addComponent(hargaSatuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(hargaSatuanLabel)
                .addGap(7, 7, 7)
                .addComponent(hargaSatuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenisProdukRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jenisProdukRadioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(kodeProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchInputPanelLayout.createSequentialGroup()
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(dataFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        barangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(barangTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchInputPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInputLabel1.setText("Masukan Kode Produk");

        searchKodeProdukInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKodeProdukInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKodeProdukInputKeyPressed(evt);
            }
        });

        searchkodeProdukButton.setBackground(new java.awt.Color(27, 26, 85));
        searchkodeProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchkodeProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        searchkodeProdukButton.setText("Cari");
        searchkodeProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkodeProdukButtonActionPerformed(evt);
            }
        });

        dataFormPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kodeProdukPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kodeProdukPanel1Layout = new javax.swing.GroupLayout(kodeProdukPanel1);
        kodeProdukPanel1.setLayout(kodeProdukPanel1Layout);
        kodeProdukPanel1Layout.setHorizontalGroup(
            kodeProdukPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        kodeProdukPanel1Layout.setVerticalGroup(
            kodeProdukPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dataFormPanel1Layout = new javax.swing.GroupLayout(dataFormPanel1);
        dataFormPanel1.setLayout(dataFormPanel1Layout);
        dataFormPanel1Layout.setHorizontalGroup(
            dataFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeProdukPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dataFormPanel1Layout.setVerticalGroup(
            dataFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(kodeProdukPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        totalHargaTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        totalHargaTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaTextAreaActionPerformed(evt);
            }
        });

        cancelButton1.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton1.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton1.setText("Batalkan");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        totalHargapanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        totalHargapanel.setText("Total Harga");

        saveButton1.setBackground(new java.awt.Color(51, 178, 73));
        saveButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton1.setForeground(new java.awt.Color(255, 255, 255));
        saveButton1.setText("Simpan");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        jumlahProdukInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jumlahProdukInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahProdukInputActionPerformed(evt);
            }
        });

        JumlahPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        JumlahPanel.setText("Jumlah");

        idPelangganPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganPanel.setText("ID Pelanggan");

        supplierDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout searchInputPanel1Layout = new javax.swing.GroupLayout(searchInputPanel1);
        searchInputPanel1.setLayout(searchInputPanel1Layout);
        searchInputPanel1Layout.setHorizontalGroup(
            searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(searchInputPanel1Layout.createSequentialGroup()
                            .addComponent(searchKodeProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(searchkodeProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(searchInputLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchInputPanel1Layout.createSequentialGroup()
                        .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(jumlahProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(searchInputPanel1Layout.createSequentialGroup()
                                .addComponent(supplierDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 115, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalHargapanel, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalHargaTextArea, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchInputPanel1Layout.createSequentialGroup()
                            .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        searchInputPanel1Layout.setVerticalGroup(
            searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchInputPanel1Layout.createSequentialGroup()
                        .addComponent(totalHargapanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalHargaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton1)
                            .addComponent(cancelButton1)))
                    .addGroup(searchInputPanel1Layout.createSequentialGroup()
                        .addComponent(searchInputLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchKodeProdukInput)
                            .addComponent(searchkodeProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchInputPanel1Layout.createSequentialGroup()
                                .addComponent(JumlahPanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchInputPanel1Layout.createSequentialGroup()
                                .addComponent(idPelangganPanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kasirTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Item", "Nama Produk", "Harga Satuan", "Jumlah", "Total"
            }
        ));
        kasirTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kasirTable);

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed

    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        SearchProdukNyaNgab(searchKodeProdukInput.getText(),Integer.parseInt(jumlahProdukInput.getText()));
        
        clearText();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void kodeProdukInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeProdukInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukInputActionPerformed

    private void namaProdukInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaProdukInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProdukInputActionPerformed

    private void radioData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData1ActionPerformed

    private void radioData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData2ActionPerformed

    private void hargaSatuanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSatuanInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSatuanInputActionPerformed

    private void jumlahInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void barangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTableMouseClicked
    }//GEN-LAST:event_barangTableMouseClicked

    private void searchKodeProdukInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKodeProdukInputKeyPressed

    }//GEN-LAST:event_searchKodeProdukInputKeyPressed

    private void searchkodeProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkodeProdukButtonActionPerformed
        try {
            jumlahKosongPembelianException();
            SearchProdukNyaNgab(searchKodeProdukInput.getText(),Integer.parseInt(jumlahProdukInput.getText()));
            clearText();
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ANGKA NGAB");
        }catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
        
    }//GEN-LAST:event_searchkodeProdukButtonActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        try {
            
            inputKosongPembelianException();
            idTransaksi= dataControl.generateId();
            int selectedIndexSingle = supplierDropdown.getSelectedIndex();
            Pelanggan selectedSingle = singleList.get(selectedIndexSingle);
            // itu masi temp
            TPenjualan dataNew = new TPenjualan(idTransaksi, selectedSingle, "2003-01-12", totalHarga);
            dataControl.insertTPenjualan(dataNew);
                
            for (int i = 0; i < pr.size(); i++) {
                BJual newB = new BJual(idTransaksi, pr.get(i), Jumlah.get(i));
                BLC.insertBJual(newB);
            }
            
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }catch(Exception e){
            System.out.println(e);
        }
        totalHarga=0;
        supplierDropdown.setSelectedIndex(-1);
        totalHargaTextArea.setText("");
        DefaultTableModel tblModel = (DefaultTableModel)kasirTable.getModel();
        tblModel.setRowCount(0);
        kasirTable.setModel(tblModel);
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void kasirTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirTableMouseClicked
        
    }//GEN-LAST:event_kasirTableMouseClicked

    private void jumlahProdukInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahProdukInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahProdukInputActionPerformed

    private void totalHargaTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaTextAreaActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        clearText();
        pr.clear();
        Jumlah.clear();
        DefaultTableModel tblModel = (DefaultTableModel)kasirTable.getModel();
        tblModel.setRowCount(0);
        kasirTable.setModel(tblModel);
        counter = 0;
    }//GEN-LAST:event_cancelButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahPanel;
    private javax.swing.JLabel KodeProdukPanel;
    private javax.swing.JTable barangTable;
    private javax.swing.JButton barukanButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JPanel dataFormPanel1;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaSatuanInput;
    private javax.swing.JLabel hargaSatuanLabel;
    private javax.swing.JLabel idPelangganPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jenisProdukRadioPanel;
    private javax.swing.JTextField jumlahInput;
    private javax.swing.JTextField jumlahProdukInput;
    private javax.swing.JTable kasirTable;
    private javax.swing.JTextField kodeProdukInput;
    private javax.swing.JPanel kodeProdukPanel;
    private javax.swing.JPanel kodeProdukPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JLabel namaData2Panel;
    private javax.swing.JTextField namaProdukInput;
    private javax.swing.JPanel namaProdukPanel;
    private javax.swing.JRadioButton radioData1;
    private javax.swing.JRadioButton radioData2;
    private javax.swing.JRadioButton radioData3;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchInputLabel;
    private javax.swing.JLabel searchInputLabel1;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JPanel searchInputPanel1;
    private javax.swing.JTextField searchKodeProdukInput;
    private javax.swing.JButton searchkodeProdukButton;
    private javax.swing.JComboBox<Pelanggan> supplierDropdown;
    private javax.swing.JButton tambahDataButton;
    private javax.swing.JTextField totalHargaTextArea;
    private javax.swing.JLabel totalHargapanel;
    // End of variables declaration//GEN-END:variables
}
