/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;
import Controller.PelangganController;
import Exception.InputKosongException;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import Model.Pelanggan;
/**
 *
 * @author LENOVO
 */
public class PelangganPanel extends javax.swing.JPanel {
    private PelangganController dataControl = new PelangganController();
    private Pelanggan dataModel = null;
    String actionPelanggan = null;
    String idPelanggan="";
    private Component rootPane;
    
    public PelangganPanel() {
        initComponents();
        setOpaque(false);     
        showTableBySearch("");
        clearTextData();
        setComponentsData(false);
        setRadioComponent(false);
        setRadioButtonValue();
        setEditDeleteButtonData(false);
        idPelangganInputTextField.setEnabled(false);
    }

    private void inputKosongDataException() throws InputKosongException{
        if(namaPelangganInputTextField.getText().isEmpty() || AlamatInputTextField1.getText().isEmpty() || nomorTeleponInputTextField2.getText().isEmpty())
            throw new InputKosongException();
    }
   
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public void setRadioButtonValue(){
        radioData4.setActionCommand("true");
        radioData5.setActionCommand("false");
        radioData6.setActionCommand("Laki-Laki");
        radioData7.setActionCommand("Perempuan");
    }
    public void setRadioComponent(boolean value){
        radioData4.setEnabled(value);
        radioData5.setEnabled(value);
        radioData6.setEnabled(value);
        radioData7.setEnabled(value);
    }
    // Pelanggan Set Komponen
    private void setComponentsData(boolean value){
        
        namaPelangganInputTextField.setEnabled(value);
        nomorTeleponInputTextField2.setEnabled(value);
        AlamatInputTextField1.setEnabled(value);
        simpanPelangganButton.setEnabled(value);
    }
   
    // Pelanggan Set Edit Delete Button
    private void setEditDeleteButtonData(boolean value){
        barukanPelangganButton.setEnabled(value);
        hapusPelangganButton.setEnabled(value);
    }
    
    // Pelanggan Clear Text
    private void clearTextData(){
        idPelangganInputTextField.setText("");
        namaPelangganInputTextField.setText("");
        nomorTeleponInputTextField2.setText("");
        AlamatInputTextField1.setText("");
        searchPelangganTextField.setText("");
        GrupSex.clearSelection();
        GrupMember.clearSelection();
    }
    public void showTableBySearch(String target){
        pelangganTable.setModel(dataControl.showTablePelanggan(target));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupSex = new javax.swing.ButtonGroup();
        GrupMember = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        searchPelangganPanel = new javax.swing.JPanel();
        searchPelangganLabel = new javax.swing.JLabel();
        searchPelangganTextField = new javax.swing.JTextField();
        searchPelangganButton = new javax.swing.JButton();
        pelangganFormPanel = new javax.swing.JPanel();
        pelangganButtonPanel = new javax.swing.JPanel();
        barukanPelangganButton = new javax.swing.JButton();
        hapusPelangganButton = new javax.swing.JButton();
        tambahPelangganButton = new javax.swing.JButton();
        idPelangganPanel = new javax.swing.JPanel();
        idPelangganInputLabel = new javax.swing.JLabel();
        idPelangganInputTextField = new javax.swing.JTextField();
        namaPelangganInputPanel = new javax.swing.JPanel();
        namaPelangganInputLabel = new javax.swing.JLabel();
        namaPelangganInputTextField = new javax.swing.JTextField();
        nomorTeleponInputLabel1 = new javax.swing.JLabel();
        nomorTeleponInputTextField2 = new javax.swing.JTextField();
        memberRadio = new javax.swing.JPanel();
        radioLabel1 = new javax.swing.JLabel();
        radioData4 = new javax.swing.JRadioButton();
        radioData5 = new javax.swing.JRadioButton();
        alamatInputPanel = new javax.swing.JPanel();
        alamatInputLabel = new javax.swing.JLabel();
        AlamatInputTextField1 = new javax.swing.JTextField();
        sexRadio = new javax.swing.JPanel();
        radioLabel2 = new javax.swing.JLabel();
        radioData6 = new javax.swing.JRadioButton();
        radioData7 = new javax.swing.JRadioButton();
        simpanPelangganButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pelangganTable = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPelangganPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPelangganLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPelangganLabel.setText("Pencarian Pelanggan");

        searchPelangganTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        searchPelangganTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPelangganTextFieldKeyTyped(evt);
            }
        });

        searchPelangganButton.setBackground(new java.awt.Color(27, 26, 85));
        searchPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPelangganButton.setText("Cari");
        searchPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPelangganPanelLayout = new javax.swing.GroupLayout(searchPelangganPanel);
        searchPelangganPanel.setLayout(searchPelangganPanelLayout);
        searchPelangganPanelLayout.setHorizontalGroup(
            searchPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPelangganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPelangganPanelLayout.createSequentialGroup()
                        .addComponent(searchPelangganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchPelangganPanelLayout.setVerticalGroup(
            searchPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPelangganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPelangganTextField)
                    .addComponent(searchPelangganButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pelangganFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        pelangganButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanPelangganButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPelangganButton.setText("Barukan");
        barukanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPelangganButtonActionPerformed(evt);
            }
        });

        hapusPelangganButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPelangganButton.setText("Hapus");
        hapusPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganButtonActionPerformed(evt);
            }
        });

        tambahPelangganButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPelangganButton.setText("Tambah");
        tambahPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pelangganButtonPanelLayout = new javax.swing.GroupLayout(pelangganButtonPanel);
        pelangganButtonPanel.setLayout(pelangganButtonPanelLayout);
        pelangganButtonPanelLayout.setHorizontalGroup(
            pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPelangganButton)
                .addGap(18, 18, 18)
                .addComponent(barukanPelangganButton)
                .addGap(18, 18, 18)
                .addComponent(hapusPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pelangganButtonPanelLayout.setVerticalGroup(
            pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPelangganButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusPelangganButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPelangganPanel.setBackground(new java.awt.Color(255, 255, 255));

        idPelangganInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganInputLabel.setText("ID Pelanggan ");

        idPelangganInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        idPelangganInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPelangganPanelLayout = new javax.swing.GroupLayout(idPelangganPanel);
        idPelangganPanel.setLayout(idPelangganPanelLayout);
        idPelangganPanelLayout.setHorizontalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelangganInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPelangganPanelLayout.setVerticalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        namaPelangganInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaPelangganInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPelangganInputLabel.setText("Nama Pelanggan");

        namaPelangganInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaPelangganInputPanelLayout = new javax.swing.GroupLayout(namaPelangganInputPanel);
        namaPelangganInputPanel.setLayout(namaPelangganInputPanelLayout);
        namaPelangganInputPanelLayout.setHorizontalGroup(
            namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPelangganInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        namaPelangganInputPanelLayout.setVerticalGroup(
            namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(namaPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorTeleponInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel1.setText("Nomor Telepon");

        nomorTeleponInputTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        memberRadio.setBackground(new java.awt.Color(255, 255, 255));

        radioLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioLabel1.setText("Member");

        GrupMember.add(radioData4);
        radioData4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData4.setText("Yes");

        GrupMember.add(radioData5);
        radioData5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData5.setText("No");
        radioData5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberRadioLayout = new javax.swing.GroupLayout(memberRadio);
        memberRadio.setLayout(memberRadioLayout);
        memberRadioLayout.setHorizontalGroup(
            memberRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLabel1)
                    .addComponent(radioData4)
                    .addComponent(radioData5))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        memberRadioLayout.setVerticalGroup(
            memberRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberRadioLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(radioLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData5))
        );

        alamatInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        alamatInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel.setText("Alamat");

        AlamatInputTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout alamatInputPanelLayout = new javax.swing.GroupLayout(alamatInputPanel);
        alamatInputPanel.setLayout(alamatInputPanelLayout);
        alamatInputPanelLayout.setHorizontalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addGroup(alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlamatInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        alamatInputPanelLayout.setVerticalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AlamatInputTextField1))
        );

        sexRadio.setBackground(new java.awt.Color(255, 255, 255));

        radioLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioLabel2.setText("Gender");

        GrupSex.add(radioData6);
        radioData6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData6.setText("Male");
        radioData6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData6ActionPerformed(evt);
            }
        });

        GrupSex.add(radioData7);
        radioData7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData7.setText("Female");
        radioData7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sexRadioLayout = new javax.swing.GroupLayout(sexRadio);
        sexRadio.setLayout(sexRadioLayout);
        sexRadioLayout.setHorizontalGroup(
            sexRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sexRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLabel2)
                    .addComponent(radioData6)
                    .addComponent(radioData7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sexRadioLayout.setVerticalGroup(
            sexRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexRadioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData7))
        );

        javax.swing.GroupLayout pelangganFormPanelLayout = new javax.swing.GroupLayout(pelangganFormPanel);
        pelangganFormPanel.setLayout(pelangganFormPanelLayout);
        pelangganFormPanelLayout.setHorizontalGroup(
            pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pelangganButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaPelangganInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomorTeleponInputLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomorTeleponInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sexRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(memberRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pelangganFormPanelLayout.setVerticalGroup(
            pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelangganButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamatInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaPelangganInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nomorTeleponInputLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomorTeleponInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sexRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memberRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        simpanPelangganButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        pelangganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        pelangganTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelangganTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pelangganTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(pelangganFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(simpanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pelangganFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPelangganTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPelangganTextFieldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n'){
            showTableBySearch(searchPelangganTextField.getText());
            clearTextData();
            setComponentsData(false);
            setEditDeleteButtonData(false);
            tambahPelangganButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchPelangganTextFieldKeyTyped

    private void searchPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPelangganButtonActionPerformed
        // TODO add your handling code here:
        showTableBySearch(searchPelangganTextField.getText());
        clearTextData();
        setComponentsData(false);
        setEditDeleteButtonData(false);
        tambahPelangganButton.setEnabled(true);
    }//GEN-LAST:event_searchPelangganButtonActionPerformed

    private void barukanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPelangganButtonActionPerformed
        // TODO add your handling code here:

        actionPelanggan = "baharui";
        setComponentsData(true);
    }//GEN-LAST:event_barukanPelangganButtonActionPerformed

    private void hapusPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganButtonActionPerformed
        // TODO add your handling code here:
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);

        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            return;
        }

        dataControl.deletePelanggan(idPelanggan);
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);
        showTableBySearch("");
        actionPelanggan = null;
        tambahPelangganButton.setEnabled(true);
    }//GEN-LAST:event_hapusPelangganButtonActionPerformed

    private void tambahPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPelangganButtonActionPerformed
        // TODO add your handling code here:

        actionPelanggan = "tambah";
        clearTextData();
        idPelanggan=dataControl.generateId();
        idPelangganInputTextField.setText(idPelanggan);
        setEditDeleteButtonData(true);
        setRadioComponent(true);
        setComponentsData(true);
    }//GEN-LAST:event_tambahPelangganButtonActionPerformed

    private void idPelangganInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganInputTextFieldActionPerformed

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        // TODO add your handling code here:
        String radio;
        boolean radio2;
        radio = GrupSex.getSelection().getActionCommand();
        radio2 = Boolean.parseBoolean(GrupMember.getSelection().getActionCommand());
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionPelanggan + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION)
        return;
        try{
            inputKosongDataException();
            if(actionPelanggan.equals("tambah")){
                dataModel = new Pelanggan(radio, radio2, idPelanggan, namaPelangganInputTextField.getText(), AlamatInputTextField1.getText(), nomorTeleponInputTextField2.getText());
                dataControl.insertPelanggan(dataModel);
            } else {
                dataModel = new Pelanggan(radio, radio2, namaPelangganInputTextField.getText(), AlamatInputTextField1.getText(), nomorTeleponInputTextField2.getText());
                dataControl.updatePelanggan(dataModel, idPelanggan);
            }
            
        }catch(InputKosongException e){
            System.out.println(e);
        }
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);
        showTableBySearch("");
        actionPelanggan = null;
        tambahPelangganButton.setEnabled(true);
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed

    private void radioData5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData5ActionPerformed

    private void radioData7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData7ActionPerformed

    private void radioData6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData6ActionPerformed

    private void pelangganTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganTableMouseClicked
        int indexSingle = -1, indexMulti = -1;
        actionPelanggan = "baharui";

        tambahPelangganButton.setEnabled(false);
        simpanPelangganButton.setEnabled(true);
        setEditDeleteButtonData(true);

        setComponentsData(false);
        setRadioComponent(false);
        GrupMember.clearSelection();
        GrupSex.clearSelection();
        int clickedRow = pelangganTable.getSelectedRow();
        TableModel tableModel = pelangganTable.getModel();

        idPelanggan = tableModel.getValueAt(clickedRow, 0).toString();

        idPelangganInputTextField.setText(idPelanggan);
        AlamatInputTextField1.setText(tableModel.getValueAt(clickedRow, 3).toString());
        namaPelangganInputTextField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        nomorTeleponInputTextField2.setText(tableModel.getValueAt(clickedRow, 1).toString());
        
        String radio1 = tableModel.getValueAt(clickedRow, 2).toString();
        String radio2 = tableModel.getValueAt(clickedRow, 5).toString();
        switch(radio2){
            case "true" :
            radioData4.setSelected(true);
            break;
            case "false" :
            radioData5.setSelected(true);
            break;
        }
        
        switch(radio1){
            case "Laki-Laki" :
            radioData6.setSelected(true);
            break;
            case "Perempuan" :
            radioData7.setSelected(true);
            break;
        }
    }//GEN-LAST:event_pelangganTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatInputTextField1;
    private javax.swing.ButtonGroup GrupMember;
    private javax.swing.ButtonGroup GrupSex;
    private javax.swing.JLabel alamatInputLabel;
    private javax.swing.JPanel alamatInputPanel;
    private javax.swing.JButton barukanPelangganButton;
    private javax.swing.JButton hapusPelangganButton;
    private javax.swing.JLabel idPelangganInputLabel;
    private javax.swing.JTextField idPelangganInputTextField;
    private javax.swing.JPanel idPelangganPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberRadio;
    private javax.swing.JLabel namaPelangganInputLabel;
    private javax.swing.JPanel namaPelangganInputPanel;
    private javax.swing.JTextField namaPelangganInputTextField;
    private javax.swing.JLabel nomorTeleponInputLabel1;
    private javax.swing.JTextField nomorTeleponInputTextField2;
    private javax.swing.JPanel pelangganButtonPanel;
    private javax.swing.JPanel pelangganFormPanel;
    private javax.swing.JTable pelangganTable;
    private javax.swing.JRadioButton radioData4;
    private javax.swing.JRadioButton radioData5;
    private javax.swing.JRadioButton radioData6;
    private javax.swing.JRadioButton radioData7;
    private javax.swing.JLabel radioLabel1;
    private javax.swing.JLabel radioLabel2;
    private javax.swing.JButton searchPelangganButton;
    private javax.swing.JLabel searchPelangganLabel;
    private javax.swing.JPanel searchPelangganPanel;
    private javax.swing.JTextField searchPelangganTextField;
    private javax.swing.JPanel sexRadio;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JButton tambahPelangganButton;
    // End of variables declaration//GEN-END:variables
}
