/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import Model.Produk;
import Controller.ProdukController;
import Exception.InputKosongException;
/**
 *
 * @author LENOVO
 */
public class ProdukPanel extends javax.swing.JPanel {
    private ProdukController dataControl = new ProdukController();
    private Produk dataModel = null;
    String actionProduk = null;
    String idProduk = "";
    private Component rootPane;
    /**
     * Creates new form inputBarangManual
     */
    public ProdukPanel() {
        initComponents();
        setOpaque(false);     
        showTableBySearch("");
        clearText();
        setComponent(false);
        setRadioComponent(false);
        setRadioButtonValue();
        setEditDeleteBtn(false);
        kodeProdukInput.setEnabled(false);
    }
    
    private void clearText(){
        kodeProdukInput.setText("");
        searchInput.setText("");
        namaProdukInput.setText("");
        hargaSatuanInput.setText("");
        jumlahInput.setText("");
        buttonGroup1.clearSelection();
    }
    
    public void setRadioComponent(boolean value){
        radioData1.setEnabled(value);
        radioData2.setEnabled(value);
        radioData3.setEnabled(value);
    }
    
    public void setRadioButtonValue(){
        radioData1.setActionCommand("Alat Rumah Tangga");
        radioData2.setActionCommand("Makanan dan Minuman");
        radioData3.setActionCommand("Kecantikan");
    }
    
    public void setEditDeleteBtn(boolean value){
        barukanButton.setEnabled(value);
        hapusButton.setEnabled(value);
    }
    
    public void setComponent(boolean value){
//        kodeProdukInput.setEnabled(value);
        namaProdukInput.setEnabled(value);
        hargaSatuanInput.setEnabled(value);
        jumlahInput.setEnabled(value);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public void showTableBySearch(String target){
        barangTable.setModel(dataControl.showTableProduk(target));
    }
    
    public void inputKosongPembelianException() throws InputKosongException{
        if(namaProdukInput.getText().isEmpty() || hargaSatuanInput.getText().isEmpty() || jumlahInput.getText().isEmpty()){
            throw new InputKosongException();
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInputLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        kodeProdukPanel = new javax.swing.JPanel();
        KodeProdukPanel = new javax.swing.JLabel();
        kodeProdukInput = new javax.swing.JTextField();
        namaProdukPanel = new javax.swing.JPanel();
        namaData2Panel = new javax.swing.JLabel();
        namaProdukInput = new javax.swing.JTextField();
        jenisProdukRadioPanel = new javax.swing.JPanel();
        radioLabel = new javax.swing.JLabel();
        radioData1 = new javax.swing.JRadioButton();
        radioData2 = new javax.swing.JRadioButton();
        radioData3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        hargaSatuanLabel = new javax.swing.JLabel();
        hargaSatuanInput = new javax.swing.JTextField();
        jumlahInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTable = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInputLabel.setText("Pencarian Produk");

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        dataFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kodeProdukPanel.setBackground(new java.awt.Color(255, 255, 255));

        KodeProdukPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        KodeProdukPanel.setText("Kode Produk");

        kodeProdukInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        kodeProdukInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeProdukInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kodeProdukPanelLayout = new javax.swing.GroupLayout(kodeProdukPanel);
        kodeProdukPanel.setLayout(kodeProdukPanelLayout);
        kodeProdukPanelLayout.setHorizontalGroup(
            kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KodeProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                        .addComponent(kodeProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodeProdukPanelLayout.setVerticalGroup(
            kodeProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeProdukPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(KodeProdukPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        namaProdukPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaData2Panel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaData2Panel.setText("Nama Produk");

        namaProdukInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namaProdukInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaProdukInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaProdukPanelLayout = new javax.swing.GroupLayout(namaProdukPanel);
        namaProdukPanel.setLayout(namaProdukPanelLayout);
        namaProdukPanelLayout.setHorizontalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaData2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(namaProdukPanelLayout.createSequentialGroup()
                        .addComponent(namaProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        namaProdukPanelLayout.setVerticalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaData2Panel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaProdukInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jenisProdukRadioPanel.setBackground(new java.awt.Color(255, 255, 255));

        radioLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioLabel.setText("Jenis Produk");

        buttonGroup1.add(radioData1);
        radioData1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData1.setText("Alat Rumah Tangga");
        radioData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioData2);
        radioData2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData2.setText("Makanan dan Minuman");
        radioData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioData3);
        radioData3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData3.setText("Kecantikan");

        javax.swing.GroupLayout jenisProdukRadioPanelLayout = new javax.swing.GroupLayout(jenisProdukRadioPanel);
        jenisProdukRadioPanel.setLayout(jenisProdukRadioPanelLayout);
        jenisProdukRadioPanelLayout.setHorizontalGroup(
            jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisProdukRadioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLabel)
                    .addComponent(radioData1)
                    .addComponent(radioData2)
                    .addComponent(radioData3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jenisProdukRadioPanelLayout.setVerticalGroup(
            jenisProdukRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisProdukRadioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        hargaSatuanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaSatuanLabel.setText("Harga Satuan");

        hargaSatuanInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        hargaSatuanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSatuanInputActionPerformed(evt);
            }
        });

        jumlahInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jumlahInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaSatuanLabel)
                    .addComponent(hargaSatuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(hargaSatuanLabel)
                .addGap(7, 7, 7)
                .addComponent(hargaSatuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenisProdukRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jenisProdukRadioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(kodeProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchInputPanelLayout.createSequentialGroup()
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(dataFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        barangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(barangTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed
        if(evt.getKeyChar()=='\n'){
            showTableBySearch(searchInput.getText());
            clearText();
            setComponent(false);
            setEditDeleteBtn(false);
            tambahDataButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTableBySearch(searchInput.getText());
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
        actionProduk = "baharui";
        setComponent(true);
        setEditDeleteBtn(true);
        setRadioComponent(false);
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        actionProduk = "hapus";

        if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionProduk + "?") == JOptionPane.CLOSED_OPTION)
        return;

        dataControl.deleteProduk(idProduk);

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        buttonGroup1.clearSelection();
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        actionProduk = "tambah";
        idProduk=dataControl.generateId();
        kodeProdukInput.setText(idProduk);
        setComponent(true);
        setRadioComponent(true);
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionProduk + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION)
        return;
        try{
            // EXCEPTION
            inputKosongPembelianException();

            // SET ATRIBUT DAN METODE PEMBAYARAN
            String radio = "";

            radio = buttonGroup1.getSelection().getActionCommand();

            if(actionProduk.equals("tambah")){
                Produk dataNew = new Produk(idProduk, namaProdukInput.getText(), radio, Integer.parseInt(jumlahInput.getText()), Double.parseDouble(hargaSatuanInput.getText()));
                dataControl.insertProduk(dataNew);
            } else {
                Produk dataNew = new Produk( namaProdukInput.getText(), radio, Integer.parseInt(jumlahInput.getText()), Double.parseDouble(hargaSatuanInput.getText()));
                dataControl.updateProduk(dataNew,idProduk);
                idProduk = "";
            }
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ANGKA NGAB");
        }

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        buttonGroup1.clearSelection();
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
        actionProduk=null;
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setEditDeleteBtn(false);
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);

        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void barangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTableMouseClicked
        actionProduk = "baharui";

        tambahDataButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
        setEditDeleteBtn(true);

        setComponent(false);
        setRadioComponent(false);
        buttonGroup1.clearSelection();

        int clickedRow = barangTable.getSelectedRow();
        TableModel tableModel = barangTable.getModel();

        idProduk = tableModel.getValueAt(clickedRow, 0).toString();
        kodeProdukInput.setText(idProduk);

        namaProdukInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        hargaSatuanInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        jumlahInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        String radio = tableModel.getValueAt(clickedRow, 2).toString();

        switch(radio){
            case "Alat Rumah Tangga" :
            radioData1.setSelected(true);
            break;
            case "Makanan dan Minuman" :
            radioData2.setSelected(true);
            break;
            case "Kecantikan":
            radioData3.setSelected(true);
            break;
        }

        cancelButton.setEnabled(true);
    }//GEN-LAST:event_barangTableMouseClicked

    private void kodeProdukInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeProdukInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukInputActionPerformed

    private void namaProdukInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaProdukInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProdukInputActionPerformed

    private void hargaSatuanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSatuanInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSatuanInputActionPerformed

    private void jumlahInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahInputActionPerformed

    private void radioData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData1ActionPerformed

    private void radioData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KodeProdukPanel;
    private javax.swing.JTable barangTable;
    private javax.swing.JButton barukanButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaSatuanInput;
    private javax.swing.JLabel hargaSatuanLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jenisProdukRadioPanel;
    private javax.swing.JTextField jumlahInput;
    private javax.swing.JTextField kodeProdukInput;
    private javax.swing.JPanel kodeProdukPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaData2Panel;
    private javax.swing.JTextField namaProdukInput;
    private javax.swing.JPanel namaProdukPanel;
    private javax.swing.JRadioButton radioData1;
    private javax.swing.JRadioButton radioData2;
    private javax.swing.JRadioButton radioData3;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchInputLabel;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JButton tambahDataButton;
    // End of variables declaration//GEN-END:variables
}
