/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import Model.Supplier;
import Controller.SupplierController;
import Exception.InputKosongException;

/**
 *
 * @author LENOVO
 */
public class SupplierPanel extends javax.swing.JPanel {
    private SupplierController dataControl = new SupplierController();
    private Supplier dataModel = null;
    String actionSupplier = null;
    String idSupplier = "";
    private Component rootPane;
    /**
     * Creates new form
     */
    public SupplierPanel() {
        initComponents();
        setOpaque(false);     
        showTableBySearch("");
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        idSupplierInputTextField.setEnabled(false);
    }
    
    private void clearText(){
        idSupplierInputTextField.setText("");
        searchSupplierTextField.setText("");
        namaSupplierInputTextField.setText("");
        instansiInputTextField.setText("");
        nomorTeleponInputTextField2.setText("");
        AlamatInputTextField1.setText("");
    }
    
    
    public void setEditDeleteBtn(boolean value){
        barukanSupplierButton.setEnabled(value);
        hapusSupplierButton.setEnabled(value);
    }
    
    public void setComponent(boolean value){
//        idSupplierInputTextField.setEnabled(value);
        namaSupplierInputTextField.setEnabled(value);
        instansiInputTextField.setEnabled(value);
        nomorTeleponInputTextField2.setEnabled(value);
        AlamatInputTextField1.setEnabled(value);
        
        simpanSupplierButton.setEnabled(value);
    }
    
    public void showTableBySearch(String target){
        supplierTable.setModel(dataControl.showTableSupplier(target));
    }
    
    public void inputKosongPembelianException() throws InputKosongException{
        if(namaSupplierInputTextField.getText().isEmpty() || instansiInputTextField.getText().isEmpty() || nomorTeleponInputTextField2.getText().isEmpty() || AlamatInputTextField1.getText().isEmpty()){
            throw new InputKosongException();
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchSupplierPanel = new javax.swing.JPanel();
        searchSupplierLabel = new javax.swing.JLabel();
        searchSupplierTextField = new javax.swing.JTextField();
        searchSupplierButton = new javax.swing.JButton();
        supplierFormPanel = new javax.swing.JPanel();
        supplierButtonPanel = new javax.swing.JPanel();
        barukanSupplierButton = new javax.swing.JButton();
        hapusSupplierButton = new javax.swing.JButton();
        tambahSupplierButton = new javax.swing.JButton();
        idSupplierPanel = new javax.swing.JPanel();
        idSupplierInputLabel = new javax.swing.JLabel();
        idSupplierInputTextField = new javax.swing.JTextField();
        namaSupplierInputPanel = new javax.swing.JPanel();
        namaSupplierInputLabel = new javax.swing.JLabel();
        namaSupplierInputTextField = new javax.swing.JTextField();
        instansiInputTextField = new javax.swing.JTextField();
        nomorTeleponInputLabel1 = new javax.swing.JLabel();
        nomorTeleponInputTextField2 = new javax.swing.JTextField();
        alamatInputPanel = new javax.swing.JPanel();
        alamatInputLabel = new javax.swing.JLabel();
        AlamatInputTextField1 = new javax.swing.JTextField();
        instansiInputLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        simpanSupplierButton = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchSupplierPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchSupplierLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchSupplierLabel.setText("Pencarian Supplier");

        searchSupplierTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        searchSupplierTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchSupplierTextFieldKeyTyped(evt);
            }
        });

        searchSupplierButton.setBackground(new java.awt.Color(27, 26, 85));
        searchSupplierButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        searchSupplierButton.setText("Cari");
        searchSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSupplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchSupplierPanelLayout = new javax.swing.GroupLayout(searchSupplierPanel);
        searchSupplierPanel.setLayout(searchSupplierPanelLayout);
        searchSupplierPanelLayout.setHorizontalGroup(
            searchSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchSupplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                    .addGroup(searchSupplierPanelLayout.createSequentialGroup()
                        .addComponent(searchSupplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchSupplierPanelLayout.setVerticalGroup(
            searchSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchSupplierLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchSupplierTextField)
                    .addComponent(searchSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supplierFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        supplierButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanSupplierButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanSupplierButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanSupplierButton.setText("Barukan");
        barukanSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanSupplierButtonActionPerformed(evt);
            }
        });

        hapusSupplierButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusSupplierButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusSupplierButton.setText("Hapus");
        hapusSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusSupplierButtonActionPerformed(evt);
            }
        });

        tambahSupplierButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahSupplierButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahSupplierButton.setText("Tambah");
        tambahSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSupplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout supplierButtonPanelLayout = new javax.swing.GroupLayout(supplierButtonPanel);
        supplierButtonPanel.setLayout(supplierButtonPanelLayout);
        supplierButtonPanelLayout.setHorizontalGroup(
            supplierButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahSupplierButton)
                .addGap(18, 18, 18)
                .addComponent(barukanSupplierButton)
                .addGap(18, 18, 18)
                .addComponent(hapusSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        supplierButtonPanelLayout.setVerticalGroup(
            supplierButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(supplierButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idSupplierPanel.setBackground(new java.awt.Color(255, 255, 255));

        idSupplierInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idSupplierInputLabel.setText("ID Supplier");

        idSupplierInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        idSupplierInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSupplierInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idSupplierPanelLayout = new javax.swing.GroupLayout(idSupplierPanel);
        idSupplierPanel.setLayout(idSupplierPanelLayout);
        idSupplierPanelLayout.setHorizontalGroup(
            idSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idSupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idSupplierInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idSupplierInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idSupplierPanelLayout.setVerticalGroup(
            idSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idSupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idSupplierInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(idSupplierInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        namaSupplierInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaSupplierInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaSupplierInputLabel.setText("Nama Supplier");

        namaSupplierInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaSupplierInputPanelLayout = new javax.swing.GroupLayout(namaSupplierInputPanel);
        namaSupplierInputPanel.setLayout(namaSupplierInputPanelLayout);
        namaSupplierInputPanelLayout.setHorizontalGroup(
            namaSupplierInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaSupplierInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaSupplierInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaSupplierInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaSupplierInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        namaSupplierInputPanelLayout.setVerticalGroup(
            namaSupplierInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaSupplierInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(namaSupplierInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSupplierInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        instansiInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        nomorTeleponInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel1.setText("Nomor Telepon");

        nomorTeleponInputTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        alamatInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        alamatInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel.setText("Alamat");

        AlamatInputTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout alamatInputPanelLayout = new javax.swing.GroupLayout(alamatInputPanel);
        alamatInputPanel.setLayout(alamatInputPanelLayout);
        alamatInputPanelLayout.setHorizontalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlamatInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alamatInputPanelLayout.setVerticalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(alamatInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlamatInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        instansiInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        instansiInputLabel1.setText("Instansi");

        javax.swing.GroupLayout supplierFormPanelLayout = new javax.swing.GroupLayout(supplierFormPanel);
        supplierFormPanel.setLayout(supplierFormPanelLayout);
        supplierFormPanelLayout.setHorizontalGroup(
            supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supplierFormPanelLayout.createSequentialGroup()
                        .addComponent(supplierButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(supplierFormPanelLayout.createSequentialGroup()
                        .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaSupplierInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instansiInputLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                                .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(instansiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nomorTeleponInputLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomorTeleponInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        supplierFormPanelLayout.setVerticalGroup(
            supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supplierFormPanelLayout.createSequentialGroup()
                        .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                                .addComponent(instansiInputLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(instansiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(supplierFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaSupplierInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nomorTeleponInputLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomorTeleponInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        simpanSupplierButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanSupplierButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanSupplierButton.setText("Simpan");
        simpanSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanSupplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(supplierFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supplierFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchSupplierTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSupplierTextFieldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n'){
            showTableBySearch(searchSupplierTextField.getText());
            clearText();
            setComponent(false);
            setEditDeleteBtn(false);
            tambahSupplierButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchSupplierTextFieldKeyTyped

    private void searchSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSupplierButtonActionPerformed
        // TODO add your handling code here:
        showTableBySearch(searchSupplierTextField.getText());
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahSupplierButton.setEnabled(true);
    }//GEN-LAST:event_searchSupplierButtonActionPerformed

    private void barukanSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanSupplierButtonActionPerformed
        // TODO add your handling code here:
        actionSupplier = "baharui";
        setComponent(true);
        setEditDeleteBtn(true);
    }//GEN-LAST:event_barukanSupplierButtonActionPerformed

    private void hapusSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusSupplierButtonActionPerformed
        // TODO add your handling code here:
        actionSupplier = "hapus";

        if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionSupplier + "?") == JOptionPane.CLOSED_OPTION)
        return;

        dataControl.deleteSupplier(idSupplier);

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        showTableBySearch("");
    }//GEN-LAST:event_hapusSupplierButtonActionPerformed

    private void tambahSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSupplierButtonActionPerformed
        // TODO add your handling code here:
        actionSupplier = "tambah";
        idSupplier=dataControl.generateId();
        idSupplierInputTextField.setText(idSupplier);
        setComponent(true);
    }//GEN-LAST:event_tambahSupplierButtonActionPerformed

    private void idSupplierInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSupplierInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSupplierInputTextFieldActionPerformed

    private void simpanSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanSupplierButtonActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionSupplier + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION)
        return;
        try{
            inputKosongPembelianException();
            if(actionSupplier.equals("tambah")){
                dataModel = new Supplier(instansiInputTextField.getText(), idSupplier, namaSupplierInputTextField.getText(), AlamatInputTextField1.getText(), nomorTeleponInputTextField2.getText());
                dataControl.insertSupplier(dataModel);
            } else {
                dataModel = new Supplier(instansiInputTextField.getText(), namaSupplierInputTextField.getText(), AlamatInputTextField1.getText(), nomorTeleponInputTextField2.getText());
                dataControl.updateSupplier(dataModel, idSupplier);
            }
        }catch(InputKosongException e){
            System.out.println(e);
        }
        
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahSupplierButton.setEnabled(true);
        showTableBySearch("");
        actionSupplier=null;
    }//GEN-LAST:event_simpanSupplierButtonActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked

        tambahSupplierButton.setEnabled(false);
        simpanSupplierButton.setEnabled(true);
        setEditDeleteBtn(true);

        setComponent(false);

        int clickedRow = supplierTable.getSelectedRow();
        TableModel tableModel = supplierTable.getModel();

        idSupplier = tableModel.getValueAt(clickedRow, 0).toString();
        idSupplierInputTextField.setText(idSupplier);
        namaSupplierInputTextField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        instansiInputTextField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        nomorTeleponInputTextField2.setText(tableModel.getValueAt(clickedRow, 3).toString());
        AlamatInputTextField1.setText(tableModel.getValueAt(clickedRow, 4).toString());
    }//GEN-LAST:event_supplierTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatInputTextField1;
    private javax.swing.JLabel alamatInputLabel;
    private javax.swing.JPanel alamatInputPanel;
    private javax.swing.JButton barukanSupplierButton;
    private javax.swing.JButton hapusSupplierButton;
    private javax.swing.JLabel idSupplierInputLabel;
    private javax.swing.JTextField idSupplierInputTextField;
    private javax.swing.JPanel idSupplierPanel;
    private javax.swing.JLabel instansiInputLabel1;
    private javax.swing.JTextField instansiInputTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaSupplierInputLabel;
    private javax.swing.JPanel namaSupplierInputPanel;
    private javax.swing.JTextField namaSupplierInputTextField;
    private javax.swing.JLabel nomorTeleponInputLabel1;
    private javax.swing.JTextField nomorTeleponInputTextField2;
    private javax.swing.JButton searchSupplierButton;
    private javax.swing.JLabel searchSupplierLabel;
    private javax.swing.JPanel searchSupplierPanel;
    private javax.swing.JTextField searchSupplierTextField;
    private javax.swing.JButton simpanSupplierButton;
    private javax.swing.JPanel supplierButtonPanel;
    private javax.swing.JPanel supplierFormPanel;
    private javax.swing.JTable supplierTable;
    private javax.swing.JButton tambahSupplierButton;
    // End of variables declaration//GEN-END:variables
}
