/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import Model.TPenjualan;
import Controller.TPenjualanController;
import Model.BJual;
import Controller.BJualController;
import Model.Produk;
import Controller.ProdukController;
import Model.Pelanggan;
import Controller.PelangganController;
import Exception.InputKosongException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import table.detailJualTable;
/**
 *
 * @author LENOVO
 */
public class TPenjualanPanel extends javax.swing.JPanel {

    /**
     * Creates new form transaksiPenjualan
     */

    private ProdukController PrC = new ProdukController();
    private TPenjualanController dataControl = new TPenjualanController();
    private BJualController BLC = new BJualController();
    private PelangganController SpC = new PelangganController();
    private List<Produk> DataProduk =  new ArrayList<>();
    private TPenjualan dataModel = null;
    private List<BJual> DataBeli = new ArrayList<>();
    private Pelanggan DataSupplier = null;
    String actionProduk = null;
    String actionBeli = null;
    String actionTransaksi = null;
    String actionSuplier = null;
    String idProduk = "";
    String idSuplier = "";
    String idTransaksi = "";
    String idBeli = "";
    private Component rootPane;
    List<Pelanggan> singleList;
    List<Produk> multiList;
    List<Integer> Jumlah = new ArrayList<>();
    int counter = 0;
    /**
     * Creates new form transaksiPembelian
     */
    public TPenjualanPanel() {
        initComponents();
        setOpaque(false);
        setPelangganToDropdown();
        setProdukToDropdown();
        showTableBySearch("");
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        idPenjualanTextArea.setEnabled(false);
    }
    
    /**
     * Creates new form inputBarangManual
     */
    public void setPelangganToDropdown(){
        singleList = SpC.showListPelanggan();
        System.out.println(singleList.size());
        for(int i = 0; i < singleList.size(); i++){
            supplierDropdown.addItem(singleList.get(i));
            System.out.println(singleList.get(i).getNama());
        }
    }

    // CUSTOMER
    public void setProdukToDropdown(){
        multiList = PrC.showListProduk();
        for(int i = 0; i < multiList.size(); i++){
            produkDropdown.addItem(multiList.get(i));
        }
    }
    private void clearText(){
        searchTransaksiInput.setText("");
        idPenjualanTextArea.setText("");
        tanggalInput.setText("");
        jumlahInput.setText("");
        supplierDropdown.setSelectedIndex(-1);
        produkDropdown.setSelectedIndex(-1);
    }
    
    
    public void setEditDeleteBtn(boolean value){
        barukanTransaksiButton.setEnabled(value);
        hapusTransaksiButton.setEnabled(value);
    }
    
    public void setComponent(boolean value){
//      idPenjualanTextArea.setEnabled(value);
        tanggalInput.setEnabled(value);
        jumlahInput.setEnabled(value);
        produkDropdown.setEnabled(value);
        supplierDropdown.setEnabled(value);
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public void showTableBySearch(String target){
        TransaksiTable.setModel(dataControl.showTableTPenjualan(target));
    }
    
    public void inputKosongPembelianException() throws InputKosongException{
        if(tanggalInput.getText().isEmpty() || supplierDropdown.getSelectedIndex() == -1 || DataProduk.isEmpty()){
            throw new InputKosongException();
        }        
    }
    public void jumlahKosongPembelianException() throws InputKosongException{
        if(jumlahInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    public void InputKeTableTemp(){
        DefaultTableModel tblModel = (DefaultTableModel)detailTable.getModel();
        Object rowData[] = new Object[2];
        for (int i = counter; i < Jumlah.size(); i++) {
            rowData[0] = DataProduk.get(i).getNama();
            rowData[1] = Jumlah.get(i);
            tblModel.addRow(rowData);
        }
    }
    
    public void InputKeArrayList(int jumlah, Produk E){
        Jumlah.add(jumlah);
        DataProduk.add(E);
        InputKeTableTemp();
        counter+=1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel8 = new javax.swing.JPanel();
        searchInputPanel8 = new javax.swing.JPanel();
        searchInputLabel8 = new javax.swing.JLabel();
        searchTransaksiInput = new javax.swing.JTextField();
        searchTransaksiButton = new javax.swing.JButton();
        dataFormPanel8 = new javax.swing.JPanel();
        buttonPanel8 = new javax.swing.JPanel();
        barukanTransaksiButton = new javax.swing.JButton();
        hapusTransaksiButton = new javax.swing.JButton();
        tambahTransaksiButton = new javax.swing.JButton();
        idPenjualan = new javax.swing.JPanel();
        idPenjualanPanel = new javax.swing.JLabel();
        idPenjualanTextArea = new javax.swing.JTextField();
        Panel = new javax.swing.JPanel();
        idPelangganPanel = new javax.swing.JLabel();
        supplierDropdown = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jumlahInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaData2Panel2 = new javax.swing.JLabel();
        produkDropdown = new javax.swing.JComboBox<>();
        tanggalPanel = new javax.swing.JPanel();
        tanggalTransaksiPanel1 = new javax.swing.JLabel();
        tanggalInput = new javax.swing.JTextField();
        detailProdukPanel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        Sape = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransaksiTable = new javax.swing.JTable();

        mainPanel8.setBackground(new java.awt.Color(255, 255, 255));

        searchInputPanel8.setBackground(new java.awt.Color(255, 255, 255));

        searchInputLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInputLabel8.setText("Pencarian Transaksi Penjualan");

        searchTransaksiInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchTransaksiInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTransaksiInputKeyPressed(evt);
            }
        });

        searchTransaksiButton.setBackground(new java.awt.Color(27, 26, 85));
        searchTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        searchTransaksiButton.setText("Cari");
        searchTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTransaksiButtonActionPerformed(evt);
            }
        });

        dataFormPanel8.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel8.setBackground(new java.awt.Color(255, 255, 255));

        barukanTransaksiButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanTransaksiButton.setText("Barukan");
        barukanTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanTransaksiButtonActionPerformed(evt);
            }
        });

        hapusTransaksiButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusTransaksiButton.setText("Hapus");
        hapusTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTransaksiButtonActionPerformed(evt);
            }
        });

        tambahTransaksiButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahTransaksiButton.setText("Tambah");
        tambahTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTransaksiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel8Layout = new javax.swing.GroupLayout(buttonPanel8);
        buttonPanel8.setLayout(buttonPanel8Layout);
        buttonPanel8Layout.setHorizontalGroup(
            buttonPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahTransaksiButton)
                .addGap(18, 18, 18)
                .addComponent(barukanTransaksiButton)
                .addGap(18, 18, 18)
                .addComponent(hapusTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanel8Layout.setVerticalGroup(
            buttonPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPenjualan.setBackground(new java.awt.Color(255, 255, 255));

        idPenjualanPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPenjualanPanel.setText("ID Penjualan");

        idPenjualanTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        idPenjualanTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPenjualanTextAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPenjualanLayout = new javax.swing.GroupLayout(idPenjualan);
        idPenjualan.setLayout(idPenjualanLayout);
        idPenjualanLayout.setHorizontalGroup(
            idPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPenjualanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(idPenjualanTextArea))
                .addContainerGap())
        );
        idPenjualanLayout.setVerticalGroup(
            idPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPenjualanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(idPenjualanPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idPenjualanTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        idPelangganPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganPanel.setText("ID Pelanggan");

        supplierDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(supplierDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(idPelangganPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierDropdown, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jumlahInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jumlahInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah");

        namaData2Panel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaData2Panel2.setText("Kode Produk");

        produkDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(namaData2Panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jumlahInput)
                    .addComponent(produkDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(namaData2Panel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produkDropdown)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        tanggalPanel.setBackground(new java.awt.Color(255, 255, 255));

        tanggalTransaksiPanel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalTransaksiPanel1.setText("Tanggal Transaksi");

        tanggalInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tanggalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tanggalPanelLayout = new javax.swing.GroupLayout(tanggalPanel);
        tanggalPanel.setLayout(tanggalPanelLayout);
        tanggalPanelLayout.setHorizontalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalTransaksiPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tanggalPanelLayout.createSequentialGroup()
                        .addComponent(tanggalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tanggalPanelLayout.setVerticalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalPanelLayout.createSequentialGroup()
                .addComponent(tanggalTransaksiPanel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        detailProdukPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        detailProdukPanel.setText("Detail Produk");

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Jumlah Produk"
            }
        ));
        detailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(detailTable);

        Sape.setText("Add Barang");
        Sape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataFormPanel8Layout = new javax.swing.GroupLayout(dataFormPanel8);
        dataFormPanel8.setLayout(dataFormPanel8Layout);
        dataFormPanel8Layout.setHorizontalGroup(
            dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tanggalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(dataFormPanel8Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dataFormPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Sape)
                        .addGap(207, 207, 207)))
                .addGap(230, 230, 230))
        );
        dataFormPanel8Layout.setVerticalGroup(
            dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormPanel8Layout.createSequentialGroup()
                        .addComponent(buttonPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dataFormPanel8Layout.createSequentialGroup()
                                .addComponent(idPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormPanel8Layout.createSequentialGroup()
                        .addComponent(detailProdukPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataFormPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sape)))
        );

        javax.swing.GroupLayout searchInputPanel8Layout = new javax.swing.GroupLayout(searchInputPanel8);
        searchInputPanel8.setLayout(searchInputPanel8Layout);
        searchInputPanel8Layout.setHorizontalGroup(
            searchInputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchInputPanel8Layout.createSequentialGroup()
                        .addComponent(searchTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(dataFormPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchInputPanel8Layout.setVerticalGroup(
            searchInputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchInputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTransaksiInput)
                    .addComponent(searchTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        TransaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TransaksiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransaksiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TransaksiTable);

        javax.swing.GroupLayout mainPanel8Layout = new javax.swing.GroupLayout(mainPanel8);
        mainPanel8.setLayout(mainPanel8Layout);
        mainPanel8Layout.setHorizontalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        mainPanel8Layout.setVerticalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTransaksiInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTransaksiInputKeyPressed
        if(evt.getKeyChar()=='\n'){
            showTableBySearch(searchTransaksiInput.getText());
            clearText();
            setComponent(false);
            setEditDeleteBtn(false);
            tambahTransaksiButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchTransaksiInputKeyPressed

    private void searchTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTransaksiButtonActionPerformed
        showTableBySearch(searchTransaksiInput.getText());
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahTransaksiButton.setEnabled(true);
    }//GEN-LAST:event_searchTransaksiButtonActionPerformed

    private void barukanTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanTransaksiButtonActionPerformed
        actionTransaksi = "baharui";
        setComponent(true);
        supplierDropdown.setEnabled(false);
        produkDropdown.setEnabled(false);
        jumlahInput.setEnabled(false);
        setEditDeleteBtn(true);
    }//GEN-LAST:event_barukanTransaksiButtonActionPerformed

    private void hapusTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTransaksiButtonActionPerformed
        actionTransaksi = "hapus";

        if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionTransaksi + "?") == JOptionPane.CLOSED_OPTION)
        return;

        dataControl.deleteTPenjualan(idTransaksi);

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahTransaksiButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_hapusTransaksiButtonActionPerformed

    private void tambahTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTransaksiButtonActionPerformed
        actionTransaksi = "tambah";
        idTransaksi = dataControl.generateId();
        idPenjualanTextArea.setText(idTransaksi);
        setComponent(true);
    }//GEN-LAST:event_tambahTransaksiButtonActionPerformed

    private void idPenjualanTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPenjualanTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPenjualanTextAreaActionPerformed

    private void jumlahInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahInputActionPerformed

    private void tanggalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try{
            inputKosongPembelianException();
            double enTotalHarga=0;
            int selectedIndexSingle = supplierDropdown.getSelectedIndex();
            Pelanggan selectedSingle = singleList.get(selectedIndexSingle);

            // KENDARAAN
            
            for (int i = 0; i < DataProduk.size(); i++) {
                    enTotalHarga += DataProduk.get(i).getHarga_satuan() * Jumlah.get(i);
            }
            
            if(actionTransaksi.equals("tambah")){
                
                TPenjualan dataNew = new TPenjualan(idTransaksi, selectedSingle, tanggalInput.getText(), enTotalHarga);
                dataControl.insertTPenjualan(dataNew);
                
                for (int i = 0; i < DataProduk.size(); i++) {
                    BJual newB = new BJual(idTransaksi, DataProduk.get(i), Jumlah.get(i));
                    BLC.insertBJual(newB);
                }
            } else {
                TPenjualan dataNew = new TPenjualan(selectedSingle, tanggalInput.getText(), enTotalHarga);
                dataControl.updateTPenjualan(dataNew, idTransaksi);
                idTransaksi = "";
            }
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahTransaksiButton.setEnabled(true);
        showTableBySearch("");
        DataProduk.clear();
        Jumlah.clear();
        DataBeli.clear();
        
        List<BJual> test= new ArrayList<>();
        detailTable.setModel(new detailJualTable(test));
        counter = 0;
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        tambahTransaksiButton.setEnabled(true);
        DataProduk.clear();
        Jumlah.clear();
        DataBeli.clear();
        List<BJual> test= new ArrayList<>();
        detailTable.setModel(new detailJualTable(test));
        counter = 0;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void TransaksiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiTableMouseClicked
        int indexSingle = -1, indexMulti = -1;
        actionTransaksi = "baharui";

        tambahTransaksiButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
        setEditDeleteBtn(true);

        setComponent(false);

        int clickedRow = TransaksiTable.getSelectedRow();
        TableModel tableModel = TransaksiTable.getModel();

        idTransaksi = tableModel.getValueAt(clickedRow, 0).toString();
        idPenjualanTextArea.setText(idTransaksi);

        for(Pelanggan first : singleList){
            if(first.getId().equals(SpC.searchPelanggan(tableModel.getValueAt(clickedRow, 1).toString()).getId())){
                indexSingle = singleList.indexOf(first);
            }
        }
        List<BJual> test = BLC.listBjual(tableModel.getValueAt(clickedRow, 0).toString());
        for (BJual bJual : test) {
            DataProduk.add(bJual.getProduk());
            Jumlah.add(bJual.getJumlah());
            counter+=1;
        }
        detailTable.setModel(BLC.showTableBJual(tableModel.getValueAt(clickedRow, 0).toString()));
        tanggalInput.setText(tableModel.getValueAt(clickedRow, 2).toString());
        supplierDropdown.setSelectedIndex(indexSingle);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_TransaksiTableMouseClicked

    private void detailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailTableMouseClicked
        // TODO add your handling code here:
        int indexSingle = -1, indexMulti = -1;
        int clickedRow = detailTable.getSelectedRow();
        TableModel tableModel = detailTable.getModel();
        
        for(Produk first : multiList){
            if(first.getKode().equals(PrC.searchProduk(tableModel.getValueAt(clickedRow, 0).toString()).getKode())){
                indexMulti = multiList.indexOf(first);
            }
        }
        
        produkDropdown.setSelectedIndex(indexMulti);
        jumlahInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
    }//GEN-LAST:event_detailTableMouseClicked

    private void SapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SapeActionPerformed
        // TODO add your handling code here:
        try {
            jumlahKosongPembelianException();
            int selectedindexMulti = produkDropdown.getSelectedIndex();
            Produk selectedSingle = multiList.get(selectedindexMulti);
            if((selectedSingle.getJumlah()-Integer.parseInt(jumlahInput.getText()))<0){
                JOptionPane.showMessageDialog(rootPane, "Habis Stok Ngab");
                return;
            }
        InputKeArrayList( Integer.parseInt(jumlahInput.getText()),selectedSingle);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ANGKA NGAB");
        }catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_SapeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Sape;
    private javax.swing.JTable TransaksiTable;
    private javax.swing.JButton barukanTransaksiButton;
    private javax.swing.JPanel buttonPanel8;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataFormPanel8;
    private javax.swing.JLabel detailProdukPanel;
    private javax.swing.JTable detailTable;
    private javax.swing.JButton hapusTransaksiButton;
    private javax.swing.JLabel idPelangganPanel;
    private javax.swing.JPanel idPenjualan;
    private javax.swing.JLabel idPenjualanPanel;
    private javax.swing.JTextField idPenjualanTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahInput;
    private javax.swing.JPanel mainPanel8;
    private javax.swing.JLabel namaData2Panel2;
    private javax.swing.JComboBox<Produk> produkDropdown;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel searchInputLabel8;
    private javax.swing.JPanel searchInputPanel8;
    private javax.swing.JButton searchTransaksiButton;
    private javax.swing.JTextField searchTransaksiInput;
    private javax.swing.JComboBox<Pelanggan> supplierDropdown;
    private javax.swing.JButton tambahTransaksiButton;
    private javax.swing.JTextField tanggalInput;
    private javax.swing.JPanel tanggalPanel;
    private javax.swing.JLabel tanggalTransaksiPanel1;
    // End of variables declaration//GEN-END:variables
}
