/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelView;

import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Component;
import Model.User;
import Controller.UserController;
import Exception.InputKosongException;

/**
 *
 * @author LENOVO
 */
public class UserPanel extends javax.swing.JPanel {
    private UserController dataControl = new UserController();
    private User dataModel = null;
    String actionUser = null;
    int idUser=0;
    private Component rootPane;
    /**
     * Creates new form newUser
     */
    public UserPanel() {
        initComponents();
        setOpaque(false);     
        showUser();
        setComponentsData(false);
        setEditDeleteButtonData(false);
        clearTextData();
    }
    
    
    private void inputKosongDataException() throws InputKosongException{
        if(usernameInputTextField.getText().isEmpty() || usernameInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
   
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    // User Set Komponen
    private void setComponentsData(boolean value){
        usernameInputTextField.setEnabled(value);
        passwordInputTextField.setEnabled(value);
    }
   
    // User Set Edit Delete Button
    private void setEditDeleteButtonData(boolean value){
        barukanKasirButton.setEnabled(value);
        hapusKasirButton.setEnabled(value);
    }
    
    // User Clear Text
    private void clearTextData(){
        usernameInputTextField.setText("");
        passwordInputTextField.setText("");
        searchKasirTextField.setText("");
    }
    
    private void showUser(){
        kasirTextArea.setText("List Kasir: \n ============= \n"+dataControl.showAllStringUser());
    }
    
    private void doSearchUser(){
        if(searchKasirTextField.getText().isEmpty())
            return;
            User c = dataControl.searchUser(searchKasirTextField.getText(),"");
            if(c == null ){
                JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
                return;
            }
            
            setEditDeleteButtonData(true);
            clearTextData();
            
            usernameInputTextField.setText(c.getUsername());
            passwordInputTextField.setText(c.getPassword());
            idUser=c.getId();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKasirPanel = new javax.swing.JPanel();
        searchKasirLabel = new javax.swing.JLabel();
        searchKasirTextField = new javax.swing.JTextField();
        searchKasirButton = new javax.swing.JButton();
        kasirFormPanel = new javax.swing.JPanel();
        kasirButtonPanel = new javax.swing.JPanel();
        barukanKasirButton = new javax.swing.JButton();
        hapusKasirButton = new javax.swing.JButton();
        tambahKasirButton = new javax.swing.JButton();
        usernamePanel = new javax.swing.JPanel();
        usernameInputLabel = new javax.swing.JLabel();
        usernameInputTextField = new javax.swing.JTextField();
        passwordInputPanel = new javax.swing.JPanel();
        passwordInputLabel = new javax.swing.JLabel();
        passwordInputTextField = new javax.swing.JTextField();
        simpanKasirButton = new javax.swing.JButton();
        kasirScrollPane = new javax.swing.JScrollPane();
        kasirTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKasirPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKasirLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKasirLabel.setText("Pencarian Kasir");

        searchKasirTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        searchKasirTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKasirTextFieldKeyTyped(evt);
            }
        });

        searchKasirButton.setBackground(new java.awt.Color(27, 26, 85));
        searchKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKasirButton.setText("Cari");
        searchKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKasirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchKasirPanelLayout = new javax.swing.GroupLayout(searchKasirPanel);
        searchKasirPanel.setLayout(searchKasirPanelLayout);
        searchKasirPanelLayout.setHorizontalGroup(
            searchKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKasirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKasirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchKasirPanelLayout.createSequentialGroup()
                        .addComponent(searchKasirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchKasirPanelLayout.setVerticalGroup(
            searchKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKasirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKasirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchKasirTextField)
                    .addComponent(searchKasirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kasirFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        kasirButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanKasirButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKasirButton.setText("Barukan");
        barukanKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKasirButtonActionPerformed(evt);
            }
        });

        hapusKasirButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKasirButton.setText("Hapus");
        hapusKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKasirButtonActionPerformed(evt);
            }
        });

        tambahKasirButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKasirButton.setText("Tambah");
        tambahKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKasirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kasirButtonPanelLayout = new javax.swing.GroupLayout(kasirButtonPanel);
        kasirButtonPanel.setLayout(kasirButtonPanelLayout);
        kasirButtonPanelLayout.setHorizontalGroup(
            kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKasirButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKasirButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        kasirButtonPanelLayout.setVerticalGroup(
            kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKasirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKasirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usernamePanel.setBackground(new java.awt.Color(255, 255, 255));

        usernameInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        usernameInputLabel.setText("Username");

        usernameInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        usernameInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(usernameInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        passwordInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        passwordInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        passwordInputLabel.setText("Password");

        passwordInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout passwordInputPanelLayout = new javax.swing.GroupLayout(passwordInputPanel);
        passwordInputPanel.setLayout(passwordInputPanelLayout);
        passwordInputPanelLayout.setHorizontalGroup(
            passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        passwordInputPanelLayout.setVerticalGroup(
            passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(passwordInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanKasirButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKasirButton.setText("Simpan");
        simpanKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKasirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kasirFormPanelLayout = new javax.swing.GroupLayout(kasirFormPanel);
        kasirFormPanel.setLayout(kasirFormPanelLayout);
        kasirFormPanelLayout.setHorizontalGroup(
            kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasirFormPanelLayout.createSequentialGroup()
                        .addComponent(kasirButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kasirFormPanelLayout.createSequentialGroup()
                        .addGroup(kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 601, Short.MAX_VALUE)
                        .addComponent(simpanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        kasirFormPanelLayout.setVerticalGroup(
            kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kasirButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simpanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kasirScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        kasirTextArea.setColumns(20);
        kasirTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        kasirTextArea.setRows(5);
        kasirScrollPane.setViewportView(kasirTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKasirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kasirFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kasirScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKasirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasirFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasirScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKasirTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKasirTextFieldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n'){
            doSearchUser();
        }
    }//GEN-LAST:event_searchKasirTextFieldKeyTyped

    private void searchKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKasirButtonActionPerformed
        // TODO add your handling code here:
        doSearchUser();
    }//GEN-LAST:event_searchKasirButtonActionPerformed

    private void simpanKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKasirButtonActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionUser + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION)
        return;
        try{
            inputKosongDataException();
            if(actionUser.equals("tambah")){
                dataModel = new User(usernameInputTextField.getText(), passwordInputTextField.getText(), 0);
                dataControl.insertUser(dataModel);
            }else{
                dataModel = new User(usernameInputTextField.getText(), passwordInputTextField.getText(), 0);
                dataControl.updateUser(dataModel, String.valueOf(idUser));
            }
            
        }catch(InputKosongException e){
            System.out.println(e);
        };
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);
        showUser();
        actionUser = null;
    }//GEN-LAST:event_simpanKasirButtonActionPerformed

    private void usernameInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputTextFieldActionPerformed

    private void tambahKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKasirButtonActionPerformed
        // TODO add your handling code here:

        actionUser = "tambah";
        clearTextData();
        setEditDeleteButtonData(true);
        setComponentsData(true);
    }//GEN-LAST:event_tambahKasirButtonActionPerformed

    private void hapusKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKasirButtonActionPerformed
        // TODO add your handling code here:
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);

        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            return;
        }

        dataControl.deleteUser(String.valueOf(idUser));
        idUser = -1;
        showUser();
    }//GEN-LAST:event_hapusKasirButtonActionPerformed

    private void barukanKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKasirButtonActionPerformed
        // TODO add your handling code here:

        actionUser = "baruhi";
        setComponentsData(true);
    }//GEN-LAST:event_barukanKasirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanKasirButton;
    private javax.swing.JButton hapusKasirButton;
    private javax.swing.JPanel kasirButtonPanel;
    private javax.swing.JPanel kasirFormPanel;
    private javax.swing.JScrollPane kasirScrollPane;
    private javax.swing.JTextArea kasirTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel passwordInputLabel;
    private javax.swing.JPanel passwordInputPanel;
    private javax.swing.JTextField passwordInputTextField;
    private javax.swing.JButton searchKasirButton;
    private javax.swing.JLabel searchKasirLabel;
    private javax.swing.JPanel searchKasirPanel;
    private javax.swing.JTextField searchKasirTextField;
    private javax.swing.JButton simpanKasirButton;
    private javax.swing.JButton tambahKasirButton;
    private javax.swing.JLabel usernameInputLabel;
    private javax.swing.JTextField usernameInputTextField;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
