/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import PanelView.KasirPanel;
import PanelView.PelangganPanel;
import PanelView.ProdukPanel;
import PanelView.SupplierPanel;
import PanelView.TPembelianPanel;
import PanelView.TPenjualanPanel;
import PanelView.UserPanel;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author iwyny
 */
public class MainView extends javax.swing.JFrame {
    private int selectedIndex = -1;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
//        setForm(new KasirPanel());
    }
    
    private void setForm(JComponent com){
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
     private void recolorDefaultSwitchPanel(){
        repaint();
        kasir.setBackground(new Color(0, 0, 0, 0));
        pembelian.setBackground(new Color(0, 0, 0, 0));
        pelanggan.setBackground(new Color(0, 0, 0, 0));
        supplier.setBackground(new Color(0, 0, 0, 0));
        barang.setBackground(new Color(0, 0, 0, 0));
        user.setBackground(new Color(0, 0, 0, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel1 = new javax.swing.JPanel();
        logoPanel1 = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        kasir = new javax.swing.JPanel();
        customerLabel1 = new javax.swing.JLabel();
        pembelian = new javax.swing.JPanel();
        kendaraanLabel1 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JPanel();
        transaksiLabel1 = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        transaksiLabelDate1 = new javax.swing.JLabel();
        barang = new javax.swing.JPanel();
        transaksiLabelDate2 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        transaksiLabelDate3 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel1.setBackground(new java.awt.Color(20, 60, 60));

        logoPanel1.setBackground(new java.awt.Color(20, 60, 60));

        logoLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 22)); // NOI18N
        logoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel1.setText("Kelontongers");

        logoLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 22)); // NOI18N
        logoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout logoPanel1Layout = new javax.swing.GroupLayout(logoPanel1);
        logoPanel1.setLayout(logoPanel1Layout);
        logoPanel1Layout.setHorizontalGroup(
            logoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logoPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        logoPanel1Layout.setVerticalGroup(
            logoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        kasir.setBackground(new java.awt.Color(20, 60, 60));
        kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirMouseClicked(evt);
            }
        });

        customerLabel1.setBackground(new java.awt.Color(20, 60, 60));
        customerLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        customerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-shopping-cart-30.png"))); // NOI18N
        customerLabel1.setText("Kasir");

        javax.swing.GroupLayout kasirLayout = new javax.swing.GroupLayout(kasir);
        kasir.setLayout(kasirLayout);
        kasirLayout.setHorizontalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kasirLayout.setVerticalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pembelian.setBackground(new java.awt.Color(20, 60, 60));
        pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianMouseClicked(evt);
            }
        });

        kendaraanLabel1.setBackground(new java.awt.Color(20, 60, 60));
        kendaraanLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kendaraanLabel1.setForeground(new java.awt.Color(255, 255, 255));
        kendaraanLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kendaraanLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi pembelian.png"))); // NOI18N
        kendaraanLabel1.setText("Transaksi Pembelian");

        javax.swing.GroupLayout pembelianLayout = new javax.swing.GroupLayout(pembelian);
        pembelian.setLayout(pembelianLayout);
        pembelianLayout.setHorizontalGroup(
            pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kendaraanLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pembelianLayout.setVerticalGroup(
            pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kendaraanLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pelanggan.setBackground(new java.awt.Color(20, 60, 60));

        transaksiLabel1.setBackground(new java.awt.Color(20, 60, 60));
        transaksiLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        transaksiLabel1.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/input customer.png"))); // NOI18N
        transaksiLabel1.setText("Input Pelanggan");
        transaksiLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pelangganLayout = new javax.swing.GroupLayout(pelanggan);
        pelanggan.setLayout(pelangganLayout);
        pelangganLayout.setHorizontalGroup(
            pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pelangganLayout.setVerticalGroup(
            pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        supplier.setBackground(new java.awt.Color(20, 60, 60));

        transaksiLabelDate1.setBackground(new java.awt.Color(20, 60, 60));
        transaksiLabelDate1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        transaksiLabelDate1.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabelDate1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabelDate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/input supplier.png"))); // NOI18N
        transaksiLabelDate1.setText("Input Supplier");
        transaksiLabelDate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiLabelDate1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout supplierLayout = new javax.swing.GroupLayout(supplier);
        supplier.setLayout(supplierLayout);
        supplierLayout.setHorizontalGroup(
            supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabelDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        supplierLayout.setVerticalGroup(
            supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabelDate1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        barang.setBackground(new java.awt.Color(20, 60, 60));

        transaksiLabelDate2.setBackground(new java.awt.Color(20, 60, 60));
        transaksiLabelDate2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        transaksiLabelDate2.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabelDate2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabelDate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/input barang.png"))); // NOI18N
        transaksiLabelDate2.setText("Input Barang Manual");
        transaksiLabelDate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiLabelDate2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barangLayout = new javax.swing.GroupLayout(barang);
        barang.setLayout(barangLayout);
        barangLayout.setHorizontalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(barangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(transaksiLabelDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        barangLayout.setVerticalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(barangLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(transaksiLabelDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );

        user.setBackground(new java.awt.Color(20, 60, 60));

        transaksiLabelDate3.setBackground(new java.awt.Color(20, 60, 60));
        transaksiLabelDate3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        transaksiLabelDate3.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabelDate3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabelDate3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customerIcon.png"))); // NOI18N
        transaksiLabelDate3.setText("User Baru");
        transaksiLabelDate3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiLabelDate3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabelDate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiLabelDate3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanel1Layout = new javax.swing.GroupLayout(sidePanel1);
        sidePanel1.setLayout(sidePanel1Layout);
        sidePanel1Layout.setHorizontalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanel1Layout.createSequentialGroup()
                        .addComponent(logoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        sidePanel1Layout.setVerticalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1020, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 211, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirMouseClicked
        if(selectedIndex == 1)
        return;

        recolorDefaultSwitchPanel();
        kasir.setBackground(new Color(241, 53, 21, 200));
        setForm(new TPenjualanPanel());
        selectedIndex = 1;
    }//GEN-LAST:event_kasirMouseClicked

    private void pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseClicked
        if(selectedIndex == 2)
        return;

        recolorDefaultSwitchPanel();
        pembelian.setBackground(new Color(241, 53, 21, 200));
        setForm(new TPembelianPanel());
        selectedIndex = 2;
    }//GEN-LAST:event_pembelianMouseClicked

    private void transaksiLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiLabel1MouseClicked
        if(selectedIndex == 3)
        return;

        recolorDefaultSwitchPanel();
        pelanggan.setBackground(new Color(241, 53, 21, 200));
        setForm(new PelangganPanel());
        selectedIndex = 3;
    }//GEN-LAST:event_transaksiLabel1MouseClicked

    private void transaksiLabelDate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiLabelDate1MouseClicked
        if(selectedIndex == 4)
        return;

        recolorDefaultSwitchPanel();
        supplier.setBackground(new Color(241, 53, 21, 200));
        setForm(new SupplierPanel());
        selectedIndex = 4;
    }//GEN-LAST:event_transaksiLabelDate1MouseClicked

    private void transaksiLabelDate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiLabelDate2MouseClicked
        if(selectedIndex == 5)
        return;

        recolorDefaultSwitchPanel();
        barang.setBackground(new Color(241, 53, 21, 200));
        setForm(new ProdukPanel());
        selectedIndex = 5;
    }//GEN-LAST:event_transaksiLabelDate2MouseClicked

    private void transaksiLabelDate3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiLabelDate3MouseClicked
        if(selectedIndex == 6)
        return;

        recolorDefaultSwitchPanel();
        user.setBackground(new Color(241, 53, 21, 200));
        setForm(new UserPanel());
        selectedIndex = 6;
    }//GEN-LAST:event_transaksiLabelDate3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barang;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel customerLabel1;
    private javax.swing.JPanel kasir;
    private javax.swing.JLabel kendaraanLabel1;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JPanel logoPanel1;
    private javax.swing.JPanel pelanggan;
    private javax.swing.JPanel pembelian;
    private javax.swing.JPanel sidePanel1;
    private javax.swing.JPanel supplier;
    private javax.swing.JLabel transaksiLabel1;
    private javax.swing.JLabel transaksiLabelDate1;
    private javax.swing.JLabel transaksiLabelDate2;
    private javax.swing.JLabel transaksiLabelDate3;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
